### ISSUE TITLE
0006-Fix-Chunk-Loading - breaks loading?

### ISSUE THREAD

**Issue by andreasdc** [SuicidalKids/IonSpigot#9]
https://github.com/SuicidalKids/IonSpigot/blob/14779ba1c7be5808d51a2a23eeb330a3db9393dc/TacoSpigot-Server-Patches/0006-Fix-Chunk-Loading.patch#L38
+        int chunkZ = org.bukkit.util.NumberConversions.floor(locX) >> 4;

Shouldn't it get locZ?
Also I think original method would get motX and motZ to load some chunks for entities like tnt, projectiles or fast moving players.

**Comment by Samsuik** [comment]
Thank you for pointing this out. 

Loading on movement is handled in getCubes, it also does a better job at this when an entity is travelling a large distance. However, it isn't guaranteed that the entity will move at all, which is where this method comes in, making sure the current chunk is loaded. The original implementation did a pretty bad job here, if the entity was moving negative along an axis it wouldn't load any chunks, fortunately this didn't affect anything due to the logic being handled in getCubes as well. 

This should be solved now with 850dda6344d75b043af6eb14baf5e0af7146fb3c

**Comment by andreasdc** [comment]
No problem, I will check if that will solve some of my chunk issues when I wake up. :)
